steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
    'gcloud', 'builds', 'submit',
    '--pack', 'image=gcr.io/$PROJECT_ID/paperform-seminar-receiver',
    '--pack', 'builder=gcr.io/buildpacks/builder:v1',
    '--pack', 'env=GOOGLE_FUNCTION_TARGET=receive_and_publish'
  ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
    'gcloud', 'run', 'deploy', 'paperform-seminar-receiver',
    '--image', 'gcr.io/$PROJECT_ID/paperform-seminar-receiver',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
