steps:
# Step 1: Install dependencies & build container with Buildpacks
- name: 'gcr.io/buildpacks/builder:v1'
  args: [
    'pack',
    'build',
    'gcr.io/$PROJECT_ID/paperform-seminar-receiver',
    '--path', '.',
    '--builder', 'gcr.io/buildpacks/builder:v1',
    '--env', 'GOOGLE_FUNCTION_TARGET=receive_and_publish',
    '--env', 'GOOGLE_FUNCTION_SIGNATURE_TYPE=http'
  ]

# Step 2: Deploy the built container to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
    'gcloud',
    'run',
    'deploy',
    'paperform-seminar-receiver',
    '--image', 'gcr.io/$PROJECT_ID/paperform-seminar-receiver',
    '--platform', 'managed',
    '--region', 'us-central1',
    '--allow-unauthenticated'
  ]
