name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy seminar-receiver as Cloud Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: avian-cosmos-458703-g3

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy receive_and_publish \
            --runtime python311 \
            --trigger-http \
            --entry-point receive_and_publish \
            --allow-unauthenticated \
            --region us-central1 \
            --source .
