name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy seminar-receiver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: avian-cosmos-458703-g3

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy seminar-receiver \
            --source . \
            --entry-point receive_and_publish \
            --runtime python311 \
            --region us-central1 \
            --project avian-cosmos-458703-g3 \
            --platform managed \
            --allow-unauthenticated
